@echo off
echo [1/2] Levantando el tunel de Cloudflare...
start /b cmd /c "C:\estudios_doctoral_v2\scripts_infraestructura\cloudflared.exe tunnel --url http://localhost:8081 > C:\estudios_doctoral_v2\scripts_infraestructura\tunnel.log 2>&1"

echo [2/2] Levantando el sistema Doctoral Nexus (Expo)...
npx expo start -c
